Repository gcivil-nyu-org/spring2020-cs-gy-9223-class, pull requests merged in 2020-04, with the labels that each got.

#294 Issue #225: Creating a GFConfig triggers creation of Event dashboards/Sensor panels for all existing events/sensors. Issue #295: View Existing Dashboards in GFConfig view
  ag_data/models.py
  mercury/forms.py
  mercury/grafanaAPI/grafana_api.py
  mercury/static/mercury/style.css
  mercury/templates/gf_configs.html
  mercury/tests/test_gf_configs.py
  mercury/urls.py
  mercury/views/gf_config.py
Labels: Front End Team

#308 Fix tests
  hardware/CommunicationsPi/find_port.py
  hardware/tests/test_find_port.py
Labels: hardware

#311 Sync hardware-team with master
  ag_data/serializers.py
  mercury/grafanaAPI/grafana_api.py
  mercury/tests/test_configure_sensors.py
  mercury/tests/test_grafana.py
  mercury/tests/test_measurement.py
  mercury/tests/test_radio_receiver.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/measurement.py
  mercury/views/radioreceiver.py
  mercury/views/sensor.py
  requirements.txt
  scripts/radioport.py
Labels: hardware

#313 Feature/transceiver tests
  hardware/CommunicationsPi/radio_transceiver.py
  hardware/tests/test_radio_transceiver.py
  requirements.txt
Labels: hardware

#358 Sync with Backend/develop
  README.md
  ag_data/admin.py
  ag_data/tests/test_simulator.py
  mercury/grafanaAPI/grafana_api.py
  mercury/tests/test_measurement.py
  mercury/views/gf_config.py
  mercury/views/measurement.py
  scripts/radioport.py
Labels: backend

#347 Sync hardware-team with master
  README.md
  ag_data/tests/test_simulator.py
  mercury/forms.py
  mercury/grafanaAPI/grafana_api.py
  mercury/static/mercury/js/events.js
  mercury/static/mercury/style.css
  mercury/templates/events.html
  mercury/templates/gf_configs.html
  mercury/tests/test_gf_configs.py
  mercury/tests/test_grafana.py
  mercury/tests/test_measurement.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/gf_config.py
  mercury/views/measurement.py
  scripts/setup.sh
  symmetricds/Makefile
  symmetricds/README.md
  symmetricds/check-properties.py
  symmetricds/configure.sql
  symmetricds/template/engine0.properties
  symmetricds/template/engine1.properties
Labels: hardware

#372 Bug - Remove excess print statements
  hardware/CommunicationsPi/find_port.py
  hardware/CommunicationsPi/logger.py
  hardware/env
Labels: hardware

#366 Frontend team
  mercury/grafanaAPI/grafana_api.py
  mercury/templates/events.html
  mercury/tests/test_event.py
  mercury/tests/test_grafana.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/sensor.py
Labels: Front End Team

#370 Active events feature complete.
  ag_data/migrations/0002_agactiveevent.py
  ag_data/models.py
  mercury/static/mercury/js/events.js
  mercury/templates/events.html
  mercury/urls.py
  mercury/views/events.py
Labels: Front End Team

#371 Grafana
  mercury/grafanaAPI/grafana_api.py
  mercury/tests/test_event.py
  mercury/tests/test_grafana.py
  mercury/urls.py
  mercury/views/events.py
Labels: Front End Team

#376 Improve formula processing
  ag_data/formulas/ingestion_engine.py
  ag_data/presets/built_in_content.py
  ag_data/presets/presets_generators.py
  ag_data/simulator.py
  ag_data/tests/test_presets_generators.py
  ag_data/tests/test_simulator.py
  ag_data/tests/test_utilities.py
  ag_data/utilities.py
Labels: backend

#380 Adapt MeasurementExchange format
  ag_data/formulas/ingestion_engine.py
  ag_data/formulas/library/system/mercury_formulas.py
  ag_data/simulator.py
  ag_data/tests/test_utilities_ingestion_engine.py
  ag_data/utilities.py
  requirements.txt
Labels: backend

#381 Simulator tests
  ag_data/simulator.py
  ag_data/tests/test_simulator.py
Labels: backend

#382 Backend master sync
  hardware/CommunicationsPi/find_port.py
  hardware/CommunicationsPi/logger.py
  hardware/env
  mercury/grafanaAPI/grafana_api.py
  mercury/templates/events.html
  mercury/tests/test_event.py
  mercury/tests/test_grafana.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/sensor.py
Labels: backend

#383 Gps sensor integration
  ag_data/presets.py
  ag_data/simulator.py
  mercury/templates/gps.html
  mercury/templates/gpspanels.html
  mercury/templates/index.html
  mercury/templates/sidebar.html
  mercury/urls.py
  mercury/views/gps.py
  mercury/views/gpspanels.py
  requirements.txt
Labels: Front End Team

#394 Grafana
  mercury/grafanaAPI/grafana_api.py
  mercury/templates/gf_configs.html
  mercury/tests/test_gf_configs.py
  mercury/tests/test_grafana.py
  mercury/urls.py
  mercury/views/gf_config.py
  mercury/views/sensor.py
Labels: Front End Team

#389 Frontend team
  ag_data/migrations/0002_agactiveevent.py
  ag_data/models.py
  mercury/grafanaAPI/grafana_api.py
  mercury/static/mercury/js/events.js
  mercury/templates/events.html
  mercury/templates/gf_configs.html
  mercury/templates/gps.html
  mercury/templates/gpspanels.html
  mercury/templates/index.html
  mercury/templates/sidebar.html
  mercury/tests/test_event.py
  mercury/tests/test_gf_configs.py
  mercury/tests/test_grafana.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/gf_config.py
  mercury/views/gps.py
  mercury/views/gpspanels.py
  mercury/views/sensor.py
  requirements.txt
Labels: Front End Team

#406 Feature/docker cache
  .travis.yml
  Dockerfile
Labels: hardware

#448 backend-team: sync with master
  .travis.yml
  Dockerfile
  ag_data/migrations/0002_agactiveevent.py
  ag_data/models.py
  hardware/CommunicationsPi/find_port.py
  hardware/CommunicationsPi/lan_client.py
  hardware/CommunicationsPi/lan_server.py
  hardware/CommunicationsPi/radio_transceiver.py
  hardware/SensorPi/main.py
  hardware/SensorPi/sense_pi.py
  hardware/SensorPi/sensehat_reader.py
  hardware/Utils/logger.py
  hardware/Utils/utils.py
  hardware/env
  hardware/main.py
  hardware/tests/test_logger.py
  hardware/tests/test_radio_transceiver.py
  hardware/tests/test_utils.py
  mercury/can.py
  mercury/can_map.py
  mercury/forms.py
  mercury/grafanaAPI/grafana_api.py
  mercury/models.py
  mercury/resources.py
  mercury/static/mercury/js/events.js
  mercury/static/mercury/js/sensor.js
  mercury/static/mercury/style.css
  mercury/templates/banner.html
  mercury/templates/events.html
  mercury/templates/gf_configs.html
  mercury/templates/gf_dashboards.html
  mercury/templates/gps.html
  mercury/templates/gpspanels.html
  mercury/templates/index.html
  mercury/templates/login.html
  mercury/templates/sensor.html
  mercury/templates/sidebar.html
  mercury/tests/test_configure_sensors.py
  mercury/tests/test_event.py
  mercury/tests/test_gf_configs.py
  mercury/tests/test_grafana.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/gf_config.py
  mercury/views/gps.py
  mercury/views/gpspanels.py
  mercury/views/sensor.py
  mysite/settings.py
  requirements.txt
Labels: backend

#455 Sync hardware-team with master
  ag_data/serializers.py
  ag_data/tests/test_serializers.py
  mercury/can.py
  mercury/can_map.py
  mercury/resources.py
  mercury/static/mercury/style.css
  mercury/templates/banner.html
  mercury/tests/test_measurement.py
  mercury/tests/test_radio_receiver.py
  mercury/urls.py
  mercury/views/measurement.py
Labels: hardware

#466 Feature/env vars
  hardware/CommunicationsPi/main.py
  hardware/CommunicationsPi/radio_transceiver.py
  hardware/SensorPi/main.py
  hardware/env
  hardware/tests/test_radio_transceiver.py
Labels: hardware

#512 CommPi Tests
  hardware/CommunicationsPi/comm_pi.py
  hardware/tests/test_comm_pi.py
  hardware/tests/test_radio_transceiver.py
Labels: hardware

#515 added lan_client tests
  hardware/CommunicationsPi/lan_client.py
  hardware/tests/test_lan_client.py
Labels: hardware

#522 Tests/lan server
  hardware/CommunicationsPi/lan_server.py
  hardware/tests/test_lan_server.py
Labels: hardware

#524 Sync hardware-team with master
  ag_data/formulas/pipeline.py
  ag_data/migrations/0003_errorlog.py
  ag_data/models.py
  ag_data/serializers.py
  ag_data/tests/test_error_log.py
  ag_data/tests/test_serializers.py
  mercury/admin.py
  mercury/forms.py
  mercury/grafanaAPI/grafana_api.py
  mercury/migrations/0019_auto_20200420_0028.py
  mercury/models.py
  mercury/static/mercury/js/sensor.js
  mercury/templates/events.html
  mercury/templates/gps.html
  mercury/templates/gpspanels.html
  mercury/templates/index.html
  mercury/templates/pitcrew.html
  mercury/templates/sidebar.html
  mercury/tests/test_configure_sensors.py
  mercury/tests/test_event.py
  mercury/tests/test_grafana.py
  mercury/tests/test_measurement.py
  mercury/tests/test_models.py
  mercury/tests/test_sensor_data.py
  mercury/tests/test_views.py
  mercury/urls.py
  mercury/views/events.py
  mercury/views/gf_config.py
  mercury/views/gps.py
  mercury/views/gpspanels.py
  mercury/views/measurement.py
  mercury/views/pitcrew.py
  mercury/views/sensor_data.py
  mysite/settings.py
Labels: hardware

#536 removed unused code
  hardware/CommunicationsPi/find_port.py
  hardware/tests/test_find_port.py
Labels: hardware

#568 Sync hardware-team with master
  README.md
  ag_data/migrations/0004_agsensortype_graph_type.py
  ag_data/models.py
  mercury/event_check.py
  mercury/forms.py
  mercury/grafanaAPI/grafana_api.py
  mercury/migrations/0019_auto_20200420_0028.py
  mercury/migrations/0020_auto_20200421_1647.py
  mercury/models.py
  mercury/static/mercury/add_grafana_host.png
  mercury/static/mercury/all_events.png
  mercury/static/mercury/all_venues.png
  mercury/static/mercury/create_event_form.png
  mercury/static/mercury/create_venue_form.png
  mercury/static/mercury/csv_structure.png
  mercury/static/mercury/gauge.png
  mercury/static/mercury/graph.png
  mercury/static/mercury/js/events.js
  mercury/static/mercury/js/gf_config.js
  mercury/static/mercury/js/sensor.js
  mercury/static/mercury/map.png
  mercury/static/mercury/style.css
  mercury/static/mercury/update_event.png
  mercury/static/mercury/update_venue.png
  mercury/templates/events.html
  mercury/templates/gf_configs.html
  mercury/templates/gf_dashboards.html
  mercury/templates/sensor.html
  mercury/tests/test_configure_sensors.py
  mercury/tests/test_event.py
  mercury/tests/test_gf_configs.py
  mercury/tests/test_grafana.py
  mercury/views/events.py
  mercury/views/gf_config.py
  mercury/views/sensor.py
  mysite/settings.py
  scripts/setup.sh
Labels: hardware

#567 SensePi Tests
  hardware/SensorPi/sense_pi.py
  hardware/tests/test_comm_pi.py
  hardware/tests/test_logger.py
  hardware/tests/test_sense_pi.py
  hardware/tests/test_utils.py
Labels: hardware

#600 Backend team assignment - Contributing.md file
  CONTRIBUTING.md
Labels: documentation

#611 Backend/sync-master
  CONTRIBUTING.md
  mercury/forms.py
  mercury/models.py
  mercury/static/mercury/add_dashboard.png
  mercury/static/mercury/existing_gf_hosts.png
  mercury/static/mercury/js/events.js
  mercury/static/mercury/js/gf_config.js
  mercury/static/mercury/ricky_bobby.jpg
  mercury/static/mercury/rusted-truck-vicky-sim-unsplash.jpg
  mercury/static/mercury/style.css
  mercury/static/mercury/view_grafana_host.png
  mercury/templates/403.html
  mercury/templates/404.html
  mercury/templates/events.html
  mercury/templates/gf_configs.html
  mercury/templates/gf_dashboards.html
  mercury/templates/sensor.html
  mercury/urls.py
  mercury/views/gf_config.py
  mercury/views/sensor.py
  mercury/views/sensor_data.py
  mysite/settings.py
Labels: backend
